apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: cleanup-step
      image: alpine
      script: |
        echo "Cleaning workspace"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-test
spec:
  steps:
    - name: run-tests
      image: python:3.11
      script: |
        pip install nose
        nosetests -v || true
